services:
    php:
        environment:
            APP_ENV: dev
        volumes:
            - .:/var/www/html
        # optional: expose FPM only inside the network (no ports needed)

    caddy:
        ports:
            - "8000:80"
        volumes:
            - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
            - .:/var/www/html:ro

    node:
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: "npm install && npm run dev"  # e.g., Vite/Encore dev server
        # if your dev server listens on 5173, expose it:
        ports:
            - "5173:5173"
