services:
    php:
        environment:
            APP_ENV: dev
        volumes:
            - .:/var/www/html
            - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
        # optional: expose FPM only inside the network (no ports needed)

    caddy:
        ports:
            - "8000:80"
        volumes:
            - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
            - .:/var/www/html:ro
